version: "3.9"
services:
  app:
    build: .
    environment:
      DB_HOST: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: "guest"
      POSTGRES_PASSWORD: "guest"
    volumes:
      - ./build/volumes:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"